### ISSUE TITLE
Peer to Peer Review - 19/11/2019

### ISSUE THREAD

**Issue by mapra99** [SofiBretz/micro_reddit#3]
## Bugs
No bugs were found :)

## Enhancements
* Implement the destroy dependence relation at database level too. 
* Add instructions for Installation and Usage of the App in README file
* Enhance Validations: Add a max limit for the comments and posts. Make sure that the submitted user name is a name, ad that the submitted email is an email.
* In the post model, add a destroy dependence relation for comments.

## Further Comments
Very nice and clean work @SofiBretz  @rmauritsson ! 👍  💪 

> Reviewed with ❤️ by Team 35: The Deadpools

**Comment by SofiBretz** [comment]
Dear Team 35: The Deadpools,

Thanks for ur advice, we made the corrections:

### Summary of Changes:

- Added length and regex validations to the models: user, post and comment.
- Implemented the destroy dependence relation at the database level.
- Readme install instructions updated.
- Added the destroy dependences to the post model on the comments. 
- Rubocop, no offenses detected.

We appreciate your review, thank you.

Regards,

Sofi and Leo.
